apiVersion: apps/v1
kind: Deployment
metadata: 
  name: first-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-app
      tier: backend
  template:
    metadata:
      labels:
        app: first-app
        tier: backend
    spec:
      containers:
      - name: first-app-fastapi
        image: lukakap/kub-first-app
    