apiVersion: v1
kind: Service
metadata:
  name: first-app-service
spec:
  selector:
    app: first-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8000
  type: LoadBalancer  
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: first-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-app
      tier: backend
  template:
    metadata:
      labels:
        app: first-app
        tier: backend
    spec:
      containers:
      - name: first-app-fastapi
        image: lukakap/kub-first-app